import { Lang } from './types';

export const FREE_TIER_REQUEST_LIMIT = 10;
export const PREMIUM_PRICE = '5 €';
export const PAYPAL_LINK = 'https://paypal.me/Erard?country.x=CH&locale.x=fr_FR';
export const TWINT_PHONE = '+41 (0) 79 679 68 11';

export const i18nStrings = {
  [Lang.EN]: {
    appName: "SEO Booster",
    tagline: "Boost Your SEO with AI",
    goPremium: "Go Premium",
    requestsLeft: "requests left",
    unlimited: "Unlimited",
    language: "Language",
    seoTool: "SEO Tool",
    history: "History",
    settings: "Settings",
    pasteTextHere: "Paste your text or topic here...",
    analysisType: "Type of Analysis",
    keywords: "Keywords",
    improveText: "Improve Text",
    competitorAnalysis: "Competitor Analysis",
    suggestion: "Suggest Text",
    tone: "Tone (Premium)",
    professional: "Professional",
    friendly: "Friendly",
    persuasive: "Persuasive",
    getResults: "Get Results",
    results: "Results",
    export: "Export",
    exportCSV: "Export CSV",
    exportPDF: "Export PDF",
    noResults: "Your results will appear here.",
    premiumFeature: "Premium Feature",
    upgradeToUnlock: "Upgrade to unlock this feature.",
    upgradePrompt: "You have reached your free limit.",
    premiumModalTitle: "Unlock Unlimited Power",
    premiumBenefits: [
      "Unlimited searches",
      "Export results (CSV, PDF)",
      "Tone customization & structure suggestions",
      "Basic competitive analysis",
      "Personal space with history",
      "Priority support"
    ],
    payWith: "Pay with",
    enterEmail: "Enter your email",
    confirmPayment: "I have paid",
    paymentConfirmed: "Payment confirmed! Welcome to Premium!",
    historyEmpty: "Your history is empty.",
    viewResult: "View Result",
    delete: "Delete",
    clearHistory: "Clear History",
    manageData: "Manage Data",
    clearPersonalData: "Clear Personal Data",
    dataCleared: "Your personal data has been cleared.",
    cookieConsent: "This website uses cookies to enhance user experience. By continuing, you agree to our use of cookies.",
    accept: "Accept",
    generating: "Generating...",
    improvedTextTitle: "Improved Text",
    keywordsTitle: "SEO Keywords",
    competitorsTitle: "Competitor Analysis",
  },
  [Lang.FR]: {
    appName: "SEO Booster",
    tagline: "Propulsez votre SEO avec l'IA",
    goPremium: "Devenir Premium",
    requestsLeft: "requêtes restantes",
    unlimited: "Illimité",
    language: "Langue",
    seoTool: "Outil SEO",
    history: "Historique",
    settings: "Paramètres",
    pasteTextHere: "Collez votre texte ou décrivez votre sujet ici...",
    analysisType: "Type d'analyse",
    keywords: "Mots-clés",
    improveText: "Optimiser le texte",
    competitorAnalysis: "Analyse de la concurrence",
    suggestion: "Proposition de texte",
    tone: "Ton (Premium)",
    professional: "Professionnel",
    friendly: "Convivial",
    persuasive: "Persuasif",
    getResults: "Lancer l'analyse",
    results: "Résultats",
    export: "Exporter",
    exportCSV: "Exporter en CSV",
    exportPDF: "Exporter en PDF",
    noResults: "Vos résultats s'afficheront ici.",
    premiumFeature: "Exclusivité Premium",
    upgradeToUnlock: "Passez à Premium pour débloquer",
    upgradePrompt: "Vous avez utilisé toutes vos requêtes gratuites.",
    premiumModalTitle: "Passez à la vitesse supérieure",
    premiumBenefits: [
      "Analyses SEO illimitées",
      "Exportation des résultats (CSV, PDF)",
      "Ton et style d'écriture personnalisables",
      "Analyse stratégique de la concurrence",
      "Historique complet de vos analyses",
      "Support client prioritaire"
    ],
    payWith: "Réglez avec",
    enterEmail: "Votre adresse e-mail",
    confirmPayment: "Activer mon compte Premium",
    paymentConfirmed: "Félicitations ! Votre compte Premium est activé.",
    historyEmpty: "Aucun historique pour le moment.",
    viewResult: "Voir le résultat",
    delete: "Supprimer",
    clearHistory: "Vider l'historique",
    manageData: "Gestion des données",
    clearPersonalData: "Supprimer mes données",
    dataCleared: "Vos données personnelles ont été supprimées.",
    cookieConsent: "Nous utilisons des cookies pour optimiser votre expérience. En continuant, vous acceptez leur utilisation.",
    accept: "J'accepte",
    generating: "Analyse en cours...",
    improvedTextTitle: "Texte optimisé",
    keywordsTitle: "Mots-clés SEO",
    competitorsTitle: "Analyse de la concurrence",
  }
};